<?php
namespace app\models\App;
use app\behaviors\CustomLogBehavior;
use app\behaviors\LabelBehavior;
use app\components\LabelComponent;
use Yii;
use yii\base\UnknownPropertyException;
use yii\db\ActiveRecord;

/**
 * Created by PhpStorm.
 * User: Andrey
 * Date: 18.03.2018
 * Time: 11:47
 */
/*
 * @var string name
 * @var created_at
 * @var priority
 * @var complete
 * @var end_date
 * @var task_id
 */
class Deal extends ActiveRecord
{

	const STATUS_COMPLETE = 1;
	const STATUS_UNCOMPLETE = 0;

    public $labels;

    public function behaviors()
    {
        return [
			CustomLogBehavior::class,
	        LabelBehavior::class,
        ];
    }

    public static function create($name, $priority, $promptly, $end_date, $labels, $task_id = null): self
    {
        $deal = new static();
        $deal->name = $name;
        $deal->created_at = time();
        $deal->promptly = $promptly;
        $deal->priority = $priority;
        $deal->end_date = $end_date;
        $deal->task_id = $task_id;
        $deal->user_id = Yii::$app->user->id;
        $deal->labels = $labels;
        return $deal;
    }

    public function edit($name, $priority, $promptly, $end_date, $labels, $task_id = null): void
    {
        $this->name = $name;
        $this->priority = $priority;
        $this->promptly = $promptly;
        $this->end_date = $end_date;
        $this->task_id = $task_id;
        $this->labels = $labels;
    }

    public function beforeSave($insert)
    {
        $this->end_date = strtotime($this->end_date);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function getEndDate()
    {
    	return date('Y-m-d H:i', $this->end_date);
    }

    public function setComplete(): void
    {
        $this->complete = self::STATUS_COMPLETE;
    }

    public function setUncomplete(): void
    {
        $this->complete = self::STATUS_UNCOMPLETE;
    }

    public static function tableName()
    {
        return '{{%deals}}';
    }

}