<?php
namespace app\models\App;
use Yii;
use yii\db\ActiveRecord;

/**
 * Created by PhpStorm.
 * User: Andrey
 * Date: 18.03.2018
 * Time: 11:47
 */
/*
 * @var string name
 * @var created_at
 * @var priority
 * @var complete
 * @var end_date
 * @var task_id
 */
class Deal extends ActiveRecord
{

    public static function create($name, $priority, $promptly, $end_date, $task_id = null): self
    {
        $deal = new static();
        $deal->name = $name;
        $deal->created_at = time();
        $deal->promptly = $promptly;
        $deal->priority = $priority;
        $deal->end_date = $end_date;
        $deal->task_id = $task_id;
        $deal->user_id = Yii::$app->user->id;
        return $deal;
    }

    public function edit($name, $priority, $promptly, $end_date, $task_id = null): void
    {
        $this->name = $name;
        $this->priority = $priority;
        $this->promptly = $promptly;
        $this->end_date = $end_date;
        $this->task_id = $task_id;
    }

    public function beforeSave($insert)
    {
        $this->end_date = strtotime($this->end_date);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $this->end_date = date('Y-m-d H:i', $this->end_date);
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        $this->end_date = date('Y-m-d H:i', $this->end_date);
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function setComplete(): void
    {
        $this->complete = 1;
    }

    public function setUncomplete(): void
    {
        $this->complete = 0;
    }

    public static function tableName()
    {
        return '{{%deals}}';
    }

}